# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f8fd7890cf98c2db64621801f1b08e74399174b892babc6fdee6a395d9e4e8cd38dad06990b82f1e3f49c1753f4c51a7860dcc787e4541895562edfc8c10dd3

test:
  secret_key_base: 5462ead4562f47f3066ebf173ec0659bea18b7b07919da425319a28a3b5e6733930525a4feca8b2dc300c25475b299bc27b2308443a7e34d7093e765697d0804

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
